### ISSUE TITLE
auto-dismantle not working?

### ISSUE THREAD

**Issue by Hydra4269** [Lambda11/let-me-fish#1]
![imagen](https://user-images.githubusercontent.com/45980748/50244291-5a8e9f80-03ae-11e9-8a85-5331ff95fa46.png)

**Comment by Owyn** [comment]
what about previous messages? didn't it say that contract was cancelled? Only you can cancel it - by hand, like through interfering with bots actions and closing its dismantling windows for example

try leaving it alone completely after starting and let it fish, that should make it work

**Comment by Hydra4269** [comment]
![imagen](https://user-images.githubusercontent.com/45980748/50244754-7c3c5680-03af-11e9-98b3-ea5105f2b26e.png)

![imagen](https://user-images.githubusercontent.com/45980748/50244770-89594580-03af-11e9-94c7-3ad5f5d959a8.png)

**Comment by Hydra4269** [comment]
this is what is on the chat, then the dismantle windows open, the "hmmm..." message appears and the fishes won't get into the dismantle windows automatically, then it stops fishing ofc

**Comment by Hydra4269** [comment]
![imagen](https://user-images.githubusercontent.com/45980748/50244924-e3f2a180-03af-11e9-8e17-6350cf719cdd.png)

this is my config file in case you need it

**Comment by Owyn** [comment]
does this happens always? have you tried again?

**Comment by Hydra4269** [comment]
yea it happened like 5 times, anyways I fixed it apparently by increasing the ACTION_DELAY_THROW_ROD i think? its working now

**Comment by Owyn** [comment]
was value in `ACTION_DELAY_THROW_ROD` standart or you lowered it first so it started not working?

**Comment by Hydra4269** [comment]
it was on standard, changed it to 8000, 8000

the only thing I touched was the DELAY_BASED_ON_FISH_TIER to false.
