### ISSUE TITLE
Unmapped Packet After update

### ISSUE THREAD

**Issue by MikaelJesus** [Lambda11/let-me-fish#10]
i got this error after update any idea how to solve it?

![capture](https://user-images.githubusercontent.com/6611467/51234805-6cbf1780-1933-11e9-885f-7fc2235558a1.PNG)

**Comment by Owyn** [comment]
That means you have to `map packets`..., so get opcodes, try this https://github.com/TerableCoder/Tera-NA-Opcodes

**Comment by MikaelJesus** [comment]
ok nevermind i fix it using this opcode  https://github.com/zc149352394/Easy-Fishing  but it doesn't work

![image](https://user-images.githubusercontent.com/6611467/51307422-449fe900-1a05-11e9-8af9-b595ceb3082a.png)

![image](https://user-images.githubusercontent.com/6611467/51307526-8df03880-1a05-11e9-8722-12a6912a9ff2.png)

**Comment by Owyn** [comment]
considering you tried to use 318 TW opcodes for your NA 312 protocol... - you must be doing it wrong, maybe even my above link should've worked if you installed it fine (try the install instruction from the readme https://github.com/Lambda11/let-me-fish/blob/master/README.md

**Comment by MikaelJesus** [comment]
ok i manage to get the opcodes now i get this error when i throw the rod

![image](https://user-images.githubusercontent.com/6611467/51369488-68bd0200-1ab9-11e9-9753-f3b5b3bd06d2.png)

**Comment by Owyn** [comment]
Almost sure that means the opcode you got for mentioned in the screenshot packet is wrong...

**Comment by LeandraTS** [comment]
@ChicknWing posted the NA codes in another fishing mod an hour ago, so all thanks must go to Him/Her.

NA opcodes.

S_FISHING_BITE = 41766
S_CHANGE_RELATION = 44429
S_USER_DEATH = 26940
C_CAST_FISHING_ROD = 21205
C_END_FISHING_MINIGAME = 39236
C_START_FISHING_MINIGAME = 20693
C_STOP_FISHING = 60129
S_CAST_FISHING_ROD = 41526
S_FISHING_CATCH = 55122
S_FISHING_STOP = 28888
S_START_FISHING_CHARGE = 40114
S_START_FISHING_MINIGAME = 46037
S_FISHING_CATCH_FAIL = 43319
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 28626
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 51289
S_RP_START_SOCIAL_ON_PROGRESS_DECOMPOSITION = 51885
S_RP_COMMIT_DECOMPOSITION_CONTRACT = 55847

**Comment by LeandraTS** [comment]
Where you put the codes to fix it?
don't know which file / files they go in to fix it too, as there are 4 map files

**Comment by Lambda11** [comment]
Updated `opcodes` folder, now it should have correct NA, TH, SEA regions opcodes, installation instruction is in the same place (readme)

**Comment by Moriang27** [comment]
RU does not working(

**Comment by Owyn** [comment]
@Moriang27 
![opcodes](https://user-images.githubusercontent.com/1309656/51764612-aa1b6600-20e6-11e9-9b46-516628a102f5.png)

**Comment by Lambda11** [comment]
added opcodes file for RU, but in cases there is no such file refer to the posted image above ^
