### ISSUE TITLE
Auto Dismantle can't transfer Fish into Dismantle-Box

### ISSUE THREAD

**Issue by Joki334** [Lambda11/let-me-fish#109]
Opens Dismantle-Box and tries to move them inside but nothing happens.
![Tera Fish Dismantle](https://user-images.githubusercontent.com/63477341/225470281-1647a3d2-6eab-43cd-80d0-11e2546f7741.JPG)

**Comment by Owyn** [comment]
it says your module is called `auto-fishing` while you are reporting a problem about  `let-me-fish` module 🤔  

anyway
1. you have wrong opcodes
2. auto-fishing is broken?
3. Tera is dead, stop beating the dead horse...

**Comment by Joki334** [comment]
Yes it does say "Auto-fishing" but also "Let Me Fish" I'm sorry for bothering you. I really don't need the Auto-Dismantle but can't seem to find away to disable it after restarting the game every time it is back to active
![Let me Fish](https://user-images.githubusercontent.com/63477341/225639133-2c491e20-df0a-46bf-9116-8249ba94dacf.JPG)
i gonna try asking artexlib about it.
Thank you for you're time and Support
