### ISSUE TITLE
Select Fish type/tier to blacklist

### ISSUE THREAD

**Issue by Calitalon** [Lambda11/let-me-fish#14]
Would it be possible to add an option to blacklist specific tiers of fish besides just the gold fish from decomposition?

I like to keep my highest tier regular fish to trade in for Metamorphic Emblems (T8 at the moment), and decompose the rest.

Thanks!

**Comment by Owyn** [comment]
> regular fish to trade in for Metamorphic Emblems

wut? you can't do anything with fish other than either decomposing it or selling it to npc trader for about 10-20 gold

**Comment by Calitalon** [comment]
In NA tera we have a federation supply merchant that allows you to trade gathered craft materials, including fish, tier 10 and below, for metamorphic emblems. Then you can use the metamorphic emblems to get enchanting materials to enchant equipment. You can sell 200 items to these merchants each day. They're always found near the fishmonger who buys fish crates.

**Comment by Owyn** [comment]
wait, you mean those npc who accept fish and give useless tokens for which you can get mats for enchanting low tier equips and other useless mats?...

with high tier rod you only get lvl 10 and lvl 9 fishes anyway, disabling all dismantling would kinda work, same as your modification

thought I doubt many ppl use those NPC and these tokens...

**Comment by Calitalon** [comment]
Yeah. those are the guys. It's useful for gearing up alts, but you're probably right on that most people don't use them anymore. I've got 5 alts so I'm a special case 🥇
