### ISSUE TITLE
Can not dismantling after Patch

### ISSUE THREAD

**Issue by herowinb** [Lambda11/let-me-fish#15]
Hi, i have problem with auto dismantling after patch SEA server. I updated opcode, all function work correct. Only have problem with auto dismantling. Tried to another mod fishing but they have same problem.
![image](https://user-images.githubusercontent.com/8396689/52894966-947cf600-31e5-11e9-8e52-6f79fc7398c3.png)

Opcode for SEA:
S_FISHING_BITE = 33881
C_START_FISHING_MINIGAME = 30163
S_START_FISHING_MINIGAME = 26026
C_END_FISHING_MINIGAME = 40715
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 36937
S_FISHING_CATCH = 54645
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 41461

**Comment by Lambda11** [comment]
> Tried to another mod fishing but they have same problem.

it's not mods who have the problem, it's your opcodes which are wrong

here
`C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 56988`
