### ISSUE TITLE
S_START_FISHING_MINIGAME

### ISSUE THREAD

**Issue by giggin** [Lambda11/let-me-fish#17]
After a month I wanted to fish again but I got this error [dispatch] hook: unmapped packet “S_START_FISHING_MINGAME”. I tried using the one provided in defs folder but it’s still the same. Playing on EU with caali’s proxy

**Comment by Owyn** [comment]
> unmapped packe

that means you don't have opcodes installed for your region, see readme

**Comment by trev44** [comment]
i also need help. ive put the required map protocol for eu in the right place. what am i doing wrong. i keep getting errors, pls help

**Comment by Owyn** [comment]
Means the place isn't right after all 🤔

**Comment by trev44** [comment]
Can you perhaps pls say where the files must exactly be put and if i must
exclude something. im from eu. Appreciated

**Comment by Owyn** [comment]
![17](https://user-images.githubusercontent.com/1309656/53994150-8b2add80-4142-11e9-8891-83db319a122a.png)

here you go
