### ISSUE TITLE
How to change timing mentioned in "Notes"

### ISSUE THREAD

**Issue by kath19x** [Lambda11/let-me-fish#18]
As per Notes:

"Yes, you can make it catch fish much faster like other cheating fishers do, even like in 2 sec lol, but server might decide to start checking how long it takes for ppl to actually catch fish and ban all unreasonably fast fishers, so only way to change this timing is to set disableAutoUpdate to true in module.json and edit top lines in the index.js file manually at your very own risk"

What are all the exact text to change in index.js?  I wan't to try it and I understand the risk.  Thank you!

**Comment by Owyn** [comment]
> top lines in the index.js file 
👀

**Comment by kath19x** [comment]
Hello, yea I read that part but I don't know what it means.  I'm editing it via notepad so I'm not aware of these so called top lines, also this is my first time in github and such.  From my end these are the top lines which does not makes sense to me.

const path = require('path');
const fs = require('fs');
const ITEMS_FISHES = ["

Hope you can clarify it.  Thanks!

**Comment by Owyn** [comment]
everything above `const path = require('path');` is what you need

**Comment by kath19x** [comment]
Ok thanks! Got it!
