### ISSUE TITLE
No fishes-to-dismantle found in your inventory, can't free up space, stopping

### ISSUE THREAD

**Issue by kath19x** [Lambda11/let-me-fish#19]
The whole fishing cycle from catching a fish to crafting the bait works fine but the problem occurs when the mod triggers the dismantling of fish 'cause the inventory is full.  It will dismantle like 20-40 fishes then will prompt an error "No fishes to dismantle found in your inventory, can't free up space, stopping" even though there are still a bunch of fishes left to be dismantled and some free inventory space.  I usually just type "fish" again and click my rod to re-fish.  How can this be fixed? Thanks!

Screenshot of the logs for reference:
[https://imgur.com/a/QVEWqEC](url)

**Comment by Lambda11** [comment]
For some reason dismantling task ran twice on your side... uploaded new version with possible fix, try updating and see if it helps

**Comment by kath19x** [comment]
I will test this out later and give you feedback asap.  Thank you

**Comment by kath19x** [comment]
Tested it and the update fixed it! Thank you so much for your work on this mod!

**Comment by kath19x** [comment]
Hello again! The same problem occurred, but not all the time, maybe it happens when it is dismantling and I'm lagging in game at the same time?

**Comment by Owyn** [comment]
latest update added some new text display into chat when doing dismantling, so a log from you would help investigate what happened

**Comment by kath19x** [comment]
I will try to replicate the problem again but it looks the same like the last time.  Anyway, I will update you guys as soon as I get the error again.

**Comment by kath19x** [comment]
I can't seem to replicate the problem,  I will close the issue for the moment and re-open once I got the problem again with screenshots.  Maybe it got messed up with the timing when I was lagging with 600+ms latency.  Anyway, thanks again for the replies!

**Comment by kath19x** [comment]
Ok after around 3-4 days of fishing, the error re-appeared. The screen got stucked on the dismanting  window being open and the fish script stopped since there are no more fish to dismantle even though there are still fishes on the bottom part of the inventory.  See attached screenshot/URL link for more info.

https://imgur.com/a/8zakvUv

**Comment by Owyn** [comment]
do you perhaps use any module for inventory cache or smth which affect inventory like fps-booser-9000 scam thing?

see it says "found 50 fishes", and then after getting rid of 20 fishes it can no longer find any fishes at all...

**Comment by kath19x** [comment]
I'm not sure.  I am just using the default Caali mods + the auto fish and translator.  I attached the screenshot of my mods

https://imgur.com/a/rD1ygOn

**Comment by Lambda11** [comment]
I think I've found the issue, should be fixed after the update, please check

**Comment by kath19x** [comment]
Done updating.  I will give feedback once I encounter the same problem.  I will close this for now.  Thank you!

**Comment by kath19x** [comment]
Encountered it twice today.  It will get stuck like the previous encounter on the dismantle window open saying no more fish even though there are still fishes left to dismantle https://imgur.com/a/aq8rO6M

**Comment by Lambda11** [comment]
Now there should be no place left for random latency delays to mess dismantling of 20+ fishes up, please try updated version, should be fixed for sure.

**Comment by kath19x** [comment]
ok will do

**Comment by kath19x** [comment]
Hi, 

Same problem,, https://imgur.com/a/puMr7Zx

**Comment by Lambda11** [comment]
Hmmm, this is my log of dismantling, always works fine and dismantles all fish so I can't really tell what is wrong on your side, no ideas currently, **but** I've made it so module won't stop if it doesn't find any fishes in your inventory before finding reported number of total fishes from the first time, also I've added a logging in case that happens to print reported inventory and found fish list, so please copy that to here next time it happens, it might show why it couldn't find any fish
```
[Proxy][Let-me-Fish] Inventory full, lets dismantle fish!
You don't have enough inventory space.
[Proxy][Let-me-Fish] Found total fishes: 48
[Proxy][Let-me-Fish] Gonna dismantle this much fishes now: 20
[Proxy][Let-me-Fish] Got the contract id for dismantling: 1050427
Dismantled "<Golden Eel> х 1". and obtained: <Fish Filetе> × 22.
Dismantled "<Golden Eel> х 1". and obtained: <Fish Filetе> × 22.
Dismantled "<Golden Eel> х 1". and obtained: <Fish Filetе> × 22.
Dismantled "<Golden Eel> х 1". and obtained: <Fish Filetе> × 22.
Dismantled "<Golden Eel> х 1". and obtained: <Fish Filetе> × 22.
Dismantled "<Makaira> х 1". and obtained: <Fish Filetе> × 25.
Dismantled "<Golden Eel> х 1". and obtained: <Fish Filetе> × 22.
Dismantled "<Golden Eel> х 1". and obtained: <Fish Filetе> × 22.
Dismantled "<Makaira> х 1". and obtained: <Fish Filetе> × 25.
Dismantled "<Makaira> х 1". and obtained: <Fish Filetе> × 25.
Dismantled "<Makaira> х 1". and obtained: <Fish Filetе> × 25.
Dismantled "<Golden Eel> х 1". and obtained: <Fish Filetе> × 22.
Dismantled "<Golden Eel> х 1". and obtained: <Fish Filetе> × 22.
Dismantled "<Golden Eel> х 1". and obtained: <Fish Filetе> × 22.
Dismantled "<Makaira> х 1". and obtained: <Fish Filetе> × 25.
Dismantled "<Golden Eel> х 1". and obtained: <Fish Filetе> × 22.
Dismantled "<Makaira> х 1". and obtained: <Fish Filetе> × 25.
Dismantled "<Golden Eel> х 1". and obtained: <Fish Filetе> × 22.
Dismantled "<Golden Eel> х 1". and obtained: <Fish Filetе> × 22.
Dismantled "<Golden Eel> х 1". and obtained: <Fish Filetе> × 22.
[Proxy][Let-me-Fish] Inventory fully updated, starting dismantling of the next batch of fish
[Proxy][Let-me-Fish] Found total fishes: 28
[Proxy][Let-me-Fish] Gonna dismantle this much fishes now: 20
Dismantled "<Golden Eel> х 1". and obtained: <Fish Filetе> × 22.
Dismantled "<Golden Eel> х 1". and obtained: <Fish Filetе> × 22.
Dismantled "<Golden Eel> х 1". and obtained: <Fish Filetе> × 22.
Dismantled "<Golden Eel> х 1". and obtained: <Fish Filetе> × 22.
Dismantled "<Makaira> х 1". and obtained: <Fish Filetе> × 25.
Dismantled "<Makaira> х 1". and obtained: <Fish Filetе> × 25.
Dismantled "<Makaira> х 1". and obtained: <Fish Filetе> × 25.
Dismantled "<Golden Eel> х 1". and obtained: <Fish Filetе> × 22.
Dismantled "<Makaira> х 1". and obtained: <Fish Filetе> × 25.
Dismantled "<Makaira> х 1". and obtained: <Fish Filetе> × 25.
Dismantled "<Golden Eel> х 1". and obtained: <Fish Filetе> × 22.
Dismantled "<Golden Eel> х 1". and obtained: <Fish Filetе> × 22.
Dismantled "<Makaira> х 1". and obtained: <Fish Filetе> × 25.
Dismantled "<Golden Eel> х 1". and obtained: <Fish Filetе> × 22.
Dismantled "<Golden Eel> х 1". and obtained: <Fish Filetе> × 22.
Dismantled "<Makaira> х 1". and obtained: <Fish Filetе> × 25.
Dismantled "<Makaira> х 1". and obtained: <Fish Filetе> × 25.
Dismantled "<Makaira> х 1". and obtained: <Fish Filetе> × 25.
Dismantled "<Makaira> х 1". and obtained: <Fish Filetе> × 25.
Dismantled "<Makaira> х 1". and obtained: <Fish Filetе> × 25.
[Proxy][Let-me-Fish] Inventory fully updated, starting dismantling of the next batch of fish
[Proxy][Let-me-Fish] Gonna dismantle this much fishes now: 8
Dismantled "<Golden Eel> х 1". and obtained: <Fish Filetе> × 22.
Dismantled "<Golden Eel> х 1". and obtained: <Fish Filetе> × 22.
Dismantled "<Golden Eel> х 1". and obtained: <Fish Filetе> × 22.
Dismantled "<Golden Eel> х 1". and obtained: <Fish Filetе> × 22.
Dismantled "<Golden Eel> х 1". and obtained: <Fish Filetе> × 22.
Dismantled "<Golden Eel> х 1". and obtained: <Fish Filetе> × 22.
Dismantled "<Golden Eel> х 1". and obtained: <Fish Filetе> × 22.
Dismantled "<Makaira> х 1". and obtained: <Fish Filetе> × 25.
[Proxy][Let-me-Fish] Fish got your bait 
```

**Comment by kath19x** [comment]
Ok, I will report back once I encounter it.  It does not always show up, sometimes entire day it won't stop, sometimes it will so its totally random, I'm guessing maybe cause of my latency spike? Like 600-2k+ ping

**Comment by Owyn** [comment]
After update after which it no waits for inventory to fully update (as command message in chat says now) ping should no longer affect it 🤔

**Comment by kath19x** [comment]
So far so good,  I will report back if I get it again. Closing this for now.  Thanks for all the work!
