### ISSUE TITLE
Disconnected While Afk

### ISSUE THREAD

**Issue by iCoMuNisTa** [Lambda11/let-me-fish#21]
using caali's proxy and I always get disconnected from the game. 
it says on log "you got disconnected by having an unstable Internet connection or any bad module" 
my friend is having The same problem

**Comment by Owyn** [comment]
do you even have https://github.com/Owyn/AFKer ?

**Comment by iCoMuNisTa** [comment]
thats The point, i was wondering about it, and downloaded, now im making the rest hahaha
