### ISSUE TITLE
Please HELP me 

### ISSUE THREAD

**Issue by zonq67** [Lambda11/let-me-fish#22]
i am use the all installation guide but 

proxy unknown command fish :(

i am play in EU server , and use Caali Proxy 

Can you give me full setupped rar ? 

Marilyn-EMRE-25#7258   -- My Discord

**Comment by kath19x** [comment]
I don't think that you can get the full setup-ed rar since you have to copy paste certain files to certain folders.  I'm using Caali too and I just followed the instructions in the readme and it worked fine

**Comment by zonq67** [comment]
> I don't think that you can get the full setup-ed rar since you have to copy paste certain files to certain folders. I'm using Caali too and I just followed the instructions in the readme and it worked fine

Can you help me for setup ? Marilyn-EMRE-25#7258  my discord , plss add me , i need your help

**Comment by zonq67** [comment]
Someone help me pls :(

**Comment by Owyn** [comment]
If it says "unknown command` but there is no error in the console, it means you haven't even installed the module itself to mods folder correctly

**Comment by Ulquio262** [comment]
when I type in "fish" it does nothing ^^ i copied all files from defs into the right folder and the 4 protocoll maps aswell but ingame i only get the messages that i use a proxy.

**Comment by Owyn** [comment]
that's cuz you haven't installed the mod itself

**Comment by kath19x** [comment]
-download the whole .zip of the mod in https://github.com/Lambda11/let-me-fish
-extract and put it on your mods folder of Caali "D:\user\Tera SEA\CaaliTeraProxy\mods" depending on where you installed it.
