### ISSUE TITLE
Disconnecting

### ISSUE THREAD

**Issue by iCoMuNisTa** [Lambda11/let-me-fish#25]
![Sem título](https://user-images.githubusercontent.com/32096279/54813162-b564bb00-4c6b-11e9-938d-32de0d4af356.png)
everytime i leave my computer i get this error and disconnect

**Comment by Owyn** [comment]
`econnreset` means your internet connection was lost for a moment - you have bad internet 🤷‍♂️

**Comment by iCoMuNisTa** [comment]
yeah i have it, but it happens to my friend too, and it started 2 days ago, i was using it like ok

**Comment by Lambda11** [comment]
It's not related to fishing bot, only to your\servers internet connection

**Comment by iCoMuNisTa** [comment]
I understand, I thought it might be something related to the server being disconnected by use of the bot, well if its only my connection than I feel safer now haha ty

**Comment by Roxycodone** [comment]
I do not have bad internet and am having the same issue. So are 3 of my friends who also do not have bad net. Issue started around the same time as icomunista

**Comment by Owyn** [comment]
Does it not happen if you don't fishbot and just afk (afk-fish) for the same amount of time?

Other people are running this for days without any problems

**Comment by Roxycodone** [comment]
No issues with getting kicked/crashing etc, EXCEPT when using this "fishbot". Seems to do just fine for about 90 minutes or so then it kicks back to server select screen. This wasn't happening before. It is recent. It is not an internet issue. The people I mentioned before with the same issue are from different states with different ISPs all with perfectly stable internet connections.

**Comment by iCoMuNisTa** [comment]
also im from another country, than... idk theres something happening, and I dont understand whats this

**Comment by Owyn** [comment]
Make sure your AFKer module is working https://github.com/Owyn/AFKer

so crafting bait \ dismantling \ fishing all work fine then for 90 minutes? and then it just stops? hmmm

pretty sure if it was admin finding out about your botting you'd be getting banned and not just disconnected instead...

are you all from the same region? NA?

**Comment by Owyn** [comment]
Just tested myself, works fine here on RU
```
[Proxy][Let-me-Fish] Fished out: 96 fishes. Time elapsed: 01:48:21. Per fish: 68 sec
[Proxy][Let-me-Fish] Fishes: 
[Proxy][Let-me-Fish] Tier 9: 66
[Proxy][Let-me-Fish] Tier 10: 30
```

not sure what could be wrong on your side, maybe wrong opcode for item deletion `fish-deleter` is doing once you reach 9k fishes?  try getting fish filet amount in inventory to 200 and see if it helps

**Comment by Roxycodone** [comment]
I will check when I get home but I am pretty sure I banked most of my filets. If all else fails, I will delete/uninstall everything and start fresh. I will let you know how it goes tonight. Thanks for the help!

**Comment by Chiiruno** [comment]
I have this problem as well, with afker and fish-deleter.
Could be connection, but I get the ECONNRESET too.

**Comment by Chiiruno** [comment]
You may be disconnecting because you have the game minimized.
Keep it in a non-minimized window or in constant full-screen, and you won't disconnect with the afker module.

**Comment by zokiopp** [comment]
I play on Eu and have the completely same problem. im 99% sure its because of the module. i have two running pc's with tera caali proxy and this module and they dc alot while displaying that error. ive tested independetly to see if i get dc while not using fish bot and i didnt got any while the pc that was using fish bot got several.

**Comment by Owyn** [comment]
🤷‍♀️  works fine on RU without any DCs for me, I can only suggest you find what exactly causes the DC:
- how much time from fishing bot start to DC passes each time
- after what actions exactly DC happens
- does it happen with other fish bots or just this one?
- does it happen if you actively fish manually without any fishbots for the same amount of time?

**Comment by zokiopp** [comment]
> 🤷‍♀️ works fine on RU for days without any DCs for me, I can only suggest you find what exactly causes the DC:
> 
> * how much time from fishing bot start to DC passes each time
> * after what actions exactly DC happens
> * does it happen with other fish bots or just this one?
> * does it happen if you actively fish manually without any fishbots for the same amount of time?

I managed to fix it by implementing the AFKer module. Its ok now :)
