### ISSUE TITLE
Error while dismanting

### ISSUE THREAD

**Issue by onyx123ff** [Lambda11/let-me-fish#26]
Getting this error then disconnecting while dismantling.
![image](https://user-images.githubusercontent.com/33734014/55089316-9eff9a80-5083-11e9-82f2-243e2b385e36.png)

**Comment by Owyn** [comment]
Does this happen every dismantling time? Screenshot of the proxy chat and console before it would also help

**Comment by onyx123ff** [comment]
No only after a long time. And not always.
Well looks like its connection problem..
![image](https://user-images.githubusercontent.com/33734014/55090100-e4709780-5084-11e9-91de-04d6d6adb1ca.png)

**Comment by onyx123ff** [comment]
Theres nothing on proxy log only that messages pop up. I started fishing at 00:20 and it stoped at 07:23.
The next proxy message is when i try to open the game and it crashes.
![image](https://user-images.githubusercontent.com/33734014/55090295-3dd8c680-5085-11e9-980f-b9e882e4da7a.png)

**Comment by Owyn** [comment]
Screens above show only disconnect messages and errors from proxy core after that (cuz it disconnected)

Even when it disconnected game chat still is shown, so if you choose to display only proxy chat in some tab and activate it before botting you can then screenshot it along with "disconnected" ingame message to see what was happening right before it

**Comment by onyx123ff** [comment]
Hmm will do that and put here next time it happens. But when i tried to come back The dismantling tab was open along with disconnected message ingame.

**Comment by onyx123ff** [comment]
Well same error and normal messages on proxy chat just this...
![image](https://user-images.githubusercontent.com/33734014/55113128-af7c3900-50b4-11e9-90ba-5485fe876fb3.png)

Maybe it doesn't support 2 clients? :)

**Comment by Owyn** [comment]
Never tried it with 2 clients, you could try with one and know for sure :)

**Comment by onyx123ff** [comment]
Well happen again. 1 client with default settings. I guess its my internet then.

**Comment by onyx123ff** [comment]
Lol i got the error again but didnt dc.Ii clicked on ok right after the message popup. It just dismantle the rest of the fishes and started fishing again.

**Comment by Lambda11** [comment]
Even thought it should not be possible, I still fixed the error above in latest version, try it.
