### ISSUE TITLE
Module doesn't work after new patch(EU)

### ISSUE THREAD

**Issue by SirBepis** [Lambda11/let-me-fish#27]
After today's patch I had a problem with my launcher ,
![image](https://user-images.githubusercontent.com/49036357/55173283-17e61b80-5184-11e9-9b05-9e24fd262223.png)
so I had to repair it.Now everytime I'm trying to fish I get this message 
![image](https://user-images.githubusercontent.com/49036357/55173348-3b10cb00-5184-11e9-9139-3141aa058a68.png)
I tried to delete the files and replace again but the error still persists.Any thoughts?

**Comment by SirBepis** [comment]
![image](https://user-images.githubusercontent.com/49036357/55174311-e1a99b80-5185-11e9-9bfc-a016b4eec717.png)
Also,that message pops up when I'm trying to enable the module.

**Comment by Owyn** [comment]
that says you don't have OPcodes for the new patch, see readme on how to get em or wait for people to post them for you after some days here (I don't play on EU so can't help)

**Comment by SirBepis** [comment]
I'm a total noob with proxy and programming in general,guess I'll just wait.Thank you!

**Comment by dikypart255** [comment]
Can you help me, how to get new op codes for SEA?

**Comment by Ulquio262** [comment]
i think i got the codes but it is still not working. I replaced the old codes with the new ones in the same protocol but still getting the same error msg as SirBepis.
What do i need to replace or do i need to reinstall the the whole mod and than use the new codes?

**Comment by SirBepis** [comment]
@Ulquio262 If you make it work and have the EU codes please let me know!Thank you in advance.

**Comment by Ulquio262** [comment]
Nice it works!
EU:  protocol.345887
C_END_FISHING_MINIGAME = 38276
C_START_FISHING_MINIGAME = 42102
S_FISHING_BITE = 57126
S_START_FISHING_MINIGAME = 36822
C_RQ_ADD_ITME_TO_DECOMPOSTION_CONTRACT = 22773

**Comment by SirBepis** [comment]
@Ulquio262
Since I'm a noob with programming , what am I supposed to do with these
codes exactly ?

**Comment by gabee99** [comment]
I created the new protocol and insterted the opcodes. Fishing seems to be working, but i get these errors at log. Any idea what did I miss?
![kép](https://user-images.githubusercontent.com/49063758/55228139-af497e00-5219-11e9-8d92-769c9e063a9c.png)

**Comment by Lambda11** [comment]
error above should be fixed with latest mod update

**Comment by gabee99** [comment]
Works perfectly. Thanks for the update!

**Comment by SirBepis** [comment]
So, is everything ok? Should I just reinstall the module?

**Comment by Lambda11** [comment]
Last update have been tested to fully work on new EU,

see installation part of readme how to put new opcodes to needed place once again
