### ISSUE TITLE
Not Auto-Dismantling and Auto-Crafting when out of bait after Patch(SEA)

### ISSUE THREAD

**Issue by Ayaksha** [Lambda11/let-me-fish#28]
Hi, After the patch on SEA, I have reconfigured everything by putting in the new opcodes for SEA and also changing the S_INVEN due to Caali-Proxy, I am able to get the contract id for dismantling after clicking on the dismantle button and if i leave it alone after it runs out of bait it does not begin auto-dismantling or auto-craft(tried with enough amount of fillet to craft) the character just stands there idle and no error is prompt for both proxy and in-game. Please help. Thank you !

**Comment by dikypart255** [comment]
Can you gift me new opcode?  Please

**Comment by Ayaksha** [comment]
the new opcode for SEA :

C_END_FISHING_MINIGAME =  50168
C_START_FISHING_MINIGAME = 58013
S_FISHING_BITE = 29236
S_START_FISHING_MINIGAME = 57576
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 56988

To Developer: Please do help me to check whether is there any issue with my opcode as well for the dismantling part. Thank you!

**Comment by dikypart255** [comment]
Thankss

**Comment by dikypart255** [comment]
Just edit in protocol.344305 map right?

**Comment by dikypart255** [comment]
Still error like this

ERROR: Error: [dispatch] hook: unmapped packet "S_START_FISHING_MINIGAME"
    at Dispatch.createHook (C:\Users\kina\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:233:23)
    at Dispatch.hook (C:\Users\kina\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:301:21)
    at Module.hook (C:\Users\kina\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\module.js:87:32)
    at Hook (C:\Users\kina\AppData\Local\Programs\CaaliTeraProxy\mods\let-me-fish-master\index.js:707:18)
    at start (C:\Users\kina\AppData\Local\Programs\CaaliTeraProxy\mods\let-me-fish-master\index.js:486:3)
    at $none (C:\Users\kina\AppData\Local\Programs\CaaliTeraProxy\mods\let-me-fish-master\index.js:88:5)
    at String.subCommandHandler (C:\Users\kina\AppData\Local\Programs\CaaliTeraProxy\mods\command\index.js:263:16)
    at CommandBase.exec (C:\Users\kina\AppData\Local\Programs\CaaliTeraProxy\mods\command\index.js:183:16)
    at hookCommand (C:\Users\kina\AppData\Local\Programs\CaaliTeraProxy\mods\command\index.js:61:30)
    at Object.CommandBase.mod.hook.event [as callback] (C:\Users\kina\AppData\Local\Programs\CaaliTeraProxy\mods\command\index.js:71:29)

**Comment by kath19x** [comment]
I'm also having a problem after the patch, I'm getting "S_START_FISHING_MINIGAME" even after getting the updated opcodes

These are my opcodes:
S_FISHING_BITE = 29236
S_START_FISHING_MINIGAME = 57576
S_FISHING_CATCH = 61637
S_REQUEST_CONTRACT = 25729
C_RQ_COMMIT_DECOMPOSITION_CONTRACT = 28456
C_RQ_START_SOCIAL_ON_PROGRESS_DECOMPOSITION = 39925
S_FISHING_CATCH_FAIL = 26569
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 46411
C_START_FISHING_MINIGAME = 58013
C_END_FISHING_MINIGAME = 50168
C_STORE_SELL_ADD_BASKET = 60107
C_STORE_COMMIT = 59186
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 53131

Why do we have a different C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT?

**Comment by kath19x** [comment]
do I have to change something else after the patch aside from the opcodes?

**Comment by Ayaksha** [comment]
Sorry my bad, your opcode for C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT is correct after i run it again, I have edited my code. If you are still having issue with S_START_FISHING_MINIGAME, it means that the place that you change your opcode is wrong.

**Comment by kath19x** [comment]
I found the issue.  I was editing the old "protocol.344305" and it should be the new "345891".  I did not know that it changes every patch or something.  I thought it is constantly "protocol.344305" that you have to edit.  

As reference for others the protocol that you have to edit and put your new opcodes can be found in "mappings.json" inside tera-data folder.  It depends per server and again changes every major  patch it seems.  Thanks.

**Comment by dikypart255** [comment]
do we have to edit all protocols with the new opcodes?
Regarding the protocol location, should all protocols be moved into the maps folder? or just move and place the protocol file for the SEA server?

**Comment by Ulquio262** [comment]
just put your OP Codes in the new "345891" protocol file and u should be good to go

**Comment by dikypart255** [comment]
Ah oke thankss

**Comment by cepyindra** [comment]
@Ayaksha sir how can i fix the S_INVEN error ? i have same problem about this.

**Comment by kath19x** [comment]
I'm on the S_INVEN error as well when inventory is full and  mod tries to dismantle

**Comment by Ayaksha** [comment]
You can change the S_INVEN by going into the Index.js folder, Ctrl+F, Search for S_INVEN, Change the number 17 to 18 which is the latest one for proxy. Afterwards you will have the same issue as me, Character won't auto dismantle and will just stand there, nothing will happen, no error prompt in-game or at proxy side. Waiting for Developer to get back.

**Comment by pawpawpon** [comment]
@kath19x yeah i have same problem. i cant even craft bait

**Comment by dikypart255** [comment]
Yeah my problem now  ita S_INVEN

**Comment by budisatria8213** [comment]
for S_INVEN error / cant dismantle / cant create bait
edit index.js and search for S_INVEN
u will find S_INVEN', 17, event =>
change 17 to 18 
save and start proxy

**Comment by cepyindra** [comment]
where is the index.js? so many index.js in proxy folder. which folder ?

**Comment by budisatria8213** [comment]
index.js inside let me fish master folder

**Comment by pawpawpon** [comment]
still cant auto craft bait and dismantle

**Comment by Lambda11** [comment]
updated inven and opcodes folder, can't test it tho

**Comment by Ayaksha** [comment]
@Lambda11 Would u prefer to have a copy of my file? so that it will be easier for you to access our problems which i guess majority of us have the same issue as me.

**Comment by alfonsolaraivan** [comment]
still not crafting.

**Comment by Ayaksha** [comment]
@Lambda11 , Hi I have tested your updated code, The problem is the same as what i had, After running out of bait, it will not auto-dismantle -> auto-craft. It will stand there idling without any error being prompt in-game chat or at the proxy side.

**Comment by SirBepis** [comment]
^
Proxy is working,you can autofish yes,things is you don't automatically craft baits once you are out and also you don't auto dismantle fishes.

**Comment by Lambda11** [comment]
Last update have been tested to fully work on new EU,

see installation part of readme how to put new opcodes to needed place once again

**Comment by kath19x** [comment]
confirmed working fine now in Tera SEA
