### ISSUE TITLE
Dismantling

### ISSUE THREAD

**Issue by MrAutismo** [Lambda11/let-me-fish#29]
Dismantling fishes when inven is full is still not working. even after updated version. OPCodes are current + no errors in console

**Comment by SirBepis** [comment]
Upvote.
Autofishing works fine but the module doesn't autodismantle and craft baits.

**Comment by Owyn** [comment]
Are you using last version? It certainly crafts baits there

**Comment by MrAutismo** [comment]
yes, also tried redownloading the mod

**Comment by redshooter14** [comment]
It works like a charm with the last version !
Thank you for the quick update :)

**Comment by SirBepis** [comment]
@redshooter14 Does it auto-craft and auto-dismantle for you?

**Comment by flytomoon88** [comment]
Hi, 
auto crafting is fine, but the auto dismantling doesn't work. can you please take a look if you have time?
thanks!

**Comment by redshooter14** [comment]
Yes it's working for me
Download the new version, replace all older files, and it should be fine.

**Comment by Zarruv** [comment]
Newest version of module, zero modifications in it. But auto dismantling is not working(saying that im busy)
Also fresh proxy only standard modules
![изображение](https://user-images.githubusercontent.com/52708964/60895793-ea723900-a26d-11e9-8523-62fbcdce21d3.png)
