### ISSUE TITLE
Error running callback for command "fish"

### ISSUE THREAD

**Issue by ninime554** [Lambda11/let-me-fish#30]
![擷取](https://user-images.githubusercontent.com/49082990/55269336-052b2e00-52cd-11e9-8b4a-a914ec49fd82.PNG)

**Comment by ninime554** [comment]
i am new to github, and i am not good at english, so it's sorry if i made something not good. i had truely put the files inside the two folders ,but it still run error. i have tried to solve this problem this days, but just couldn't resolve it.

**Comment by Ghost6922112269** [comment]
Region? (Currently available opcodes in this repo are EU, SEA/TH only).

That error means the opcodes are not mapped.
If you're EU, then make sure you put the file `opcodes\protocol.345887.map` into `node_modules\tera-data\map\` If you're using caali's proxy, and it will work.
For SEA/TH, file `opcodes\protocol.345891.map` so it works.
For TW, JP regions, the opcodes not available right now, so you will have to get them by yourself ([see how](https://github.com/Lambda11/let-me-fish#notes)), or wait until they will be available.

**Comment by ninime554** [comment]
TW.
but i do not know that much about program. is it means i can only give it up...

**Comment by Owyn** [comment]
![Untitled](https://user-images.githubusercontent.com/1309656/55275903-de392000-52fd-11e9-9d8c-73e133e58d29.png)
