### ISSUE TITLE
Please add autosell to npc instead of dismantling.

### ISSUE THREAD

**Issue by kath19x** [Lambda11/let-me-fish#31]
Can you please consider it?  There are fishing spots like in Vexatus that the npc is just near and you can sell the fishes instead of dismantling them.  I got so many useless fish fillets on my bank :(

Fishing got revamped on the patch so you can get max 25,000 gold selling fishes/BAF to the fishmonger, it also it gives around 1m exp.  Very good to level and earn money while you are AFK and busy doing other stuff.  Kindly consider it.  Thank you!

**Comment by kinsyu** [comment]
There's another module that does that already.

**Comment by kath19x** [comment]
@kinsyu  But it is not working right now

**Comment by Owyn** [comment]
I think that one had just sell to summoned merchant? And here we'r talking about fishmongers which give exp and trash mats tokens for exchange for your fish, with 70lvl update that'd definitely a good idea to use him

**Comment by kath19x** [comment]
That mod can also sell to npc like in Vexatus swamp fish spot, the npc is just near the water so you can easily sell, no need for the npc scroll as long as npc is 6m away.  I'm already half way to 66 just fishing and got lots of gold since fishmonger increased the daily fish you can sell to 30 or 50 for vip, which is a lot compared to 3 before.

**Comment by Owyn** [comment]
But still, 30 fishes easily fits into inventory, usually when you come to check your fish-bot it would already have 30+ fishes in the inventory, so you could just manually sell those each day, is there even a need to automate this?

**Comment by kath19x** [comment]
Of course there is a need to automate it, that is the whole point of using a fish bot/mod, to AFK for a very long time w/o human interaction.

Imagine multiple accounts/fishers doing AFK fishing,
-you automate leveling since fishing now gives exp
-you automate leveling "processing" profession since crafting baits gives crafting level
-you automate gold production like a passive income, being AFK fishing and doing in real life stuff at the same time

**Comment by Owyn** [comment]
I mean, that's just one action, once per day, akin to just starting your fishing bot once

**Comment by kath19x** [comment]
And that "one action" is enough to stop the entire fishing activity if you AFK'ed for very long hours and waste time since you did not manage to take that one action.  Also, it is not one action per day, I find my self going back to npc selling stuff at least 10 times per day and this is just one account.

**Comment by kath19x** [comment]
closing it for the mean time, hopefully the dev will consider this feature,  Thanks for the work!

**Comment by Owyn** [comment]
> it also it gives around 1m exp.

just checked - it doesn't give any exp at all. Only catching fish does.

also keep in mind that accepted fish is rotated in the NPC, it might not accept any fish from the area you left your bot in.

personally I'd just turn dismantling of gold fish off and keep em in the inv till I check on them to give em to the npc later if I have the mood
