### ISSUE TITLE
QoL fix

### ISSUE THREAD

**Issue by Lolibunny** [Lambda11/let-me-fish#34]
Previous version first used up the bait i had selected before reverting to crafting bait when i ran out but in the new version i HAVE TO use the crafted bait and cant fish with other bait (emp bait etc). Possible to fix for better QoL please?

**Comment by Owyn** [comment]
Yea, noticed this yesterday, it's the new patch which removed the warning when you try to fish without any bait... it's being looked into now to fix

**Comment by Lambda11** [comment]
fixed in latest version :-)

**Comment by Lolibunny** [comment]
Lambda i dont think you get what i meant previously. Say i have EMP bait in my inventory, and i want to use those first so i selected EMP bait. Previously, your code will continue to use the selected bait i have (EMP bait) and when ALL EMP bait runs out it will switch to crafting NORMAL bait. Now i cant use any bait that i have besides the saved NORMAL bait. Your code will stop after ONE EMP catch and craft normal bait immediately.

I would like to use the good bait first (to maximize level of fishes caught).
