### ISSUE TITLE
Fishing cancelled

### ISSUE THREAD

**Issue by DHuangs** [Lambda11/let-me-fish#36]
my module can working normally before today's update 
After update , new issue happened .
Such as the following message.
Fishing cancelled... due to lag? Retrying...
------------------------------------------------------
Why are we not fishing?... Maybe no bait used?
Why are we not fishing?... Maybe no bait used?
Why are we not fishing?... Maybe no bait used?
Why are we not fishing?... Maybe no bait used?
Why are we not fishing?... Maybe no bait used?
Why are we not fishing?... Maybe no bait used?
Fishing cancelled... due to lag? Retrying...
Why are we not fishing?... Maybe no bait used?
Fishing cancelled... due to lag? Retrying...
Why are we not fishing?... Maybe no bait used?
Negotiations are taking long time to finish...lets wait a bit more
-------------------------------------------------------
it repeatedly freezes the bait, starts the bait, and freezes the bait, and then stops working.

Can you please help solve this problem? 
Thanks.

**Comment by Lambda11** [comment]
Pushed a fix
