### ISSUE TITLE
QoL Fix

### ISSUE THREAD

**Issue by Lolibunny** [Lambda11/let-me-fish#39]
Lambda i dont think you get what i meant previously. Say i have EMP bait in my inventory, and i want to use those first so i selected EMP bait. Previously, your code will continue to use the selected bait i have (EMP bait) and when ALL EMP bait runs out it will switch to crafting NORMAL bait. Now i cant use any bait that i have besides the saved NORMAL bait. Your code will stop after ONE EMP catch and craft normal bait immediately.

I would like to use the good bait first (to maximize level of fishes caught).

_Originally posted by @Lolibunny in https://github.com/Lambda11/let-me-fish/issues/34#issuecomment-481716614_

**Comment by Owyn** [comment]
>Your code will stop after ONE EMP catch and craft normal bait immediately.

Just craft normal bait once BEFORE using EMP one to have some of it

**Comment by Lolibunny** [comment]
Hi Owyn, your workaround works though wouldnt have known if you didnt share since the previous version wasnt like that... thank you!
