### ISSUE TITLE
Let-me-fish Cannot be broken down automatically

### ISSUE THREAD

**Issue by unkonwBBBB** [Lambda11/let-me-fish#4]
Dear author, I am from China. My English is very poor, so I wrote this with Google Translate. I encountered a doubt in using your module (after starting let-me-fish). Step 1 2 3 I encountered an error in 2 ( Maybe it's a regional problem. The module doesn't recognize my broken fish. It is displayed on the proxy channel ("now fish with this id would get auto-dismantled:0"). It can't be decomposed after my back pack is full of fish. Because the code for the fish is not recognized. I tried to save the file and then edit it. I replaced the 0 in "toDismantle"{ "0": true" with the item ID of the fish in my backpack and tried to break the fish in the backpack again with the command "fish load". This time I can identify the fish normally, but in the backpack. The fish can't be broken down because the fish can't be added to the decomposition list. Can you help me? Thank you very much.

**Comment by unkonwBBBB** [comment]
由于时差的关系，我可能不能及时回复你 请原谅我

**Comment by unkonwBBBB** [comment]
Due to the time difference, I may not be able to respond to you in time. Please forgive me.

**Comment by unkonwBBBB** [comment]
The client is TW

**Comment by unkonwBBBB** [comment]
When the module starts to add fish, it will prompt “Other jobs are in progress”.

**Comment by Lambda11** [comment]
> TW
> fish can not be added
you don't have `opcodes` for your region, or have those wrong (incorrect) -> that is the reason it does not work

![clipboard image](https://user-images.githubusercontent.com/5417634/50360894-bc980200-0572-11e9-89e9-3b3b994ef2c3.jpg)

**Comment by unkonwBBBB** [comment]
Thank you for your answer. I will try to solve it.

**Comment by unkonwBBBB** [comment]
Thank you very much, after I adjusted the opcode correctly, the module is ready for use. Thank you very much for making such a great module.

**Comment by Owyn** [comment]
If you'd like - you could upload your opcodes file so other ppl from your region won't be coming here with similar problem...

**Comment by unkonwBBBB** [comment]
I solved the problem with the opcode, but the module does not continue to fish after the fish is broken down. But the prompt can not clear the backpack occupation, end fishing? The following are the operation codes of the TW area.(S_FISHING_BITE = 64160
S_CHANGE_RELATION = 43994
S_FISHING_CATCH = 58883
S_START_FISHING_MINIGAME = 52023
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 39986
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 43402
C_START_FISHING_MINIGAME = 29778
C_END_FISHING_MINIGAME = 47071
S_FISHING_CATCH_FAIL = 26122
S_END_PRODUCE = 60602
S_RP_COMMIT_DECOMPOSITION_CONTRACT = 59499
C_RQ_COMMIT_DECOMPOSITION_CONTRACT = 24926
S_SPAWN_SERVANT = 53875
S_CHANGE_SERVANT_ENERGY = 60127)

**Comment by unkonwBBBB** [comment]
Is it because of the delay? I tried to increase ACTION_DELAY_THROW_ROD but I haven't tested it yet.

**Comment by Owyn** [comment]
any messages in the proxy chat or console? does broken down fish dissapear from inventory?

`C_RQ_COMMIT_DECOMPOSITION_CONTRACT` is a standart opcode, you should not change or add it, Caali proxy already has it

**Comment by Owyn** [comment]
if you mean `No fishes-to-dismantle found in your inventory, can't free up space, stopping`

it happens when it does not find anything to dismantle during dismantling, it can happen  during dismantling because:
1) inventory got full, so it tried to free up space
2) you had no fish filets to craft bait, so it tried to get those

anyway, there should have been another proxy message before that explaining

**Comment by unkonwBBBB** [comment]
when the probrem has happened  if change dealy it will Become normal

**Comment by Owyn** [comment]
Post screenshot of your proxy chat messages. - it will help.

what delay did you change? from what and to what?

**Comment by unkonwBBBB** [comment]
proxy  let me fish (inventory lets dismantle fish)
proxy  let me fish gonna dismantle this much fishes
proxy let me fish got the contract id for dismantle4770119
proxy let me fish contrart for dismantling cancelled(not by let me fish),retrying dismantling sequence...
proxy let me fish Not fishes-to-dismantle found in your inventory

**Comment by unkonwBBBB** [comment]
![image](https://user-images.githubusercontent.com/42921702/50395361-68716580-079e-11e9-940d-462d51cb1acc.png)

**Comment by Owyn** [comment]
what's cancelling the contract? it specifically says it is done `(not by let-me-fish)` - only way I know that would happen - if the user closes dismantle window with his own hands hmmm...

**Comment by unkonwBBBB** [comment]
This situation does not happen again, but I did not close it because I am not in front of the computer.

**Comment by unkonwBBBB** [comment]
I don't know when this problem happened, but sometimes he is normal. I didn't close it.

**Comment by Owyn** [comment]
Try looking inside system messages chat tab, maybe there it will be written what happened before\after this message.

anyway, now it was changed to what happens when contract is cancelled - instead of retrying dismantling it would retry fishing from the start of throwing the rod, that should fix it.

**Comment by unkonwBBBB** [comment]
Do you know how this problem happened?

**Comment by Owyn** [comment]
No idea, that's why I asked you to look up system messages to get to know it when it happens

**Comment by unkonwBBBB** [comment]
![image](https://user-images.githubusercontent.com/42921702/50419861-1bf55b00-086e-11e9-86c4-22c763fe4ef8.png)

**Comment by Owyn** [comment]
I mean not only `proxy chat` but also `system chat` messages, there could be some useful information

btw, that is the old version of the module which stops, new one retries throwing the rod instead and doesn't stop there...

**Comment by unkonwBBBB** [comment]
Sorry to reply to you for so long, because I forgot to use the new version of the module has been solved. Maybe the new module has been retried to solve it.
