### ISSUE TITLE
Cant log in on my character

### ISSUE THREAD

**Issue by Gladimus** [Lambda11/let-me-fish#40]
@Lambda11 i have this issue that I alt tabbed while fishing, did some stuff and after a while I alt tabbed back into the game and I couldnt use anything in my inventory and i couldnt use skills so i relogged and now I cant log onto the character that i was fishing on. I can log in on other ones, but not that one. Also my friends told me that in the guildlist my character is online, but on their friendslist its offline. Some friends told me that my character was probably banned ? Idk tho, I didnt get any official info about that. I dont know if the issue is server related ? Is it just a massive server lag, or is the issue due to the module or is it just a ban ? Maybe its a known issue? Please help

**Comment by Owyn** [comment]
🤷‍♀️ 
try asking tera support (without saying anything about auto-fishing)

admins don't ban single characters, only whole accounts

**Comment by Gladimus** [comment]
A friend told me maybe some of my game files got corrupted so I'm trying to reinstall. If it doesnt work I'll wait for a server reset, meaning maintenance, if that doesnt work either I'll try by support.

Ty for the response @Owyn. Thats what i thought aswell, didnt get any info about it so its not a ban i think. But no idea if the fishing mod caused it ?

**Comment by Owyn** [comment]
Probably you leveled your character to 66+ with fishing while having some of game files (videos) deleted by yourself, and now game checks for their presence on 66+ lvl characters and exits the game if those are not found (cuz you can't play the game without seeing their new amazing game videos for 66+ lvl ofc - that's what koreans had in mind when implementing this).

Or no idea.

**Comment by Jenoside** [comment]
Uh you're probably doomzoned, that character will be stuck until maintenance probably, but still have no idea how auto fishing modules cause it. Seems to randomly occur during the dismantling process. Heard of this happening to a few people already.

**Comment by Gladimus** [comment]
Oh yeah @Jenoside i saw the dismantling window before it all bugged. And I've done some research about the doomzone. Its definately the doomzone, since the symptoms match. Its not the fault of the fishing module, but "cheating" in general. I've read that proxy devs have made some kind of "traps" for ppl that use bots and mods that give an unfair advantage over ppl that dont use them. Doomzone is that "trap". So my character is stuck between being logged in and out and i cant do anything about it except wait for maintenance. I advise the creator of the fishing mod to warn ppl about this "doomzone". Until now I had no idea this could happen. Thanks for the help though.

**Comment by Owyn** [comment]
Unless you specifically installed some "doomzone me if I cheat" module - proxy won't do it 🤷‍♀️

**Comment by Jenoside** [comment]
Yeah it shouldn't do it, but for some reason it occurs. Also happens with the other publicly available fish bot. Even if it's rare, still possible somehow.
https://github.com/SoliaRdi/auto-fishing/issues/78

**Comment by Gladimus** [comment]
So basically it shouldn't happen and its rare and I got unlucky? :(
When i asked for help in proxy discord, they immediately knew, it was because of the fishing module, so apparently they are familiar with the issue smh...
I wouldn't use the bot if 
a) half the server wasn't using it 
b) it wasn't the only viable option to get xp without months of grinding
Now I'm a bit afraid tho tbh. Any chance this will get a fix in the future?

**Comment by Owyn** [comment]
If there's a chance to get to know what exactly triggered it - then yea - there'd also be a chance to "fix" it

unless ofc admins didn't just implement a "doomzone this guy" button and having fun with it on fish-botters or smth

**Comment by Jenoside** [comment]
Well, from what I heard, if you have a lag spike while putting fish into the dismantle window, there's a chance it can happen, no idea other than that.

**Comment by Owyn** [comment]
That shoudn't be it, other module, with which it also happens, waits for server response that fish was put in successfully before trying to put the next one, so everything exactly same as a human would do while lagging

**Comment by Jenoside** [comment]
No idea then, but always seems to happen during the dismantling process, can't be purely random though. Seeing more and more people getting doomzoned since patch 80 hit though :^)
