### ISSUE TITLE
Defs/OPcodes likely need update after tera update

### ISSUE THREAD

**Issue by Chiiruno** [Lambda11/let-me-fish#41]
Just a friendly reminder if relevant, feel free to close.
Tera proxy itself needs an update too it would seem.

**Comment by giggin** [comment]
S_FISHING_BITE = 35300
C_START_FISHING_MINIGAME = 25896
S_START_FISHING_MINIGAME = 61667
C_END_FISHING_MINIGAME = 38335
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 46975

**Comment by giggin** [comment]
What do I do with them?

**Comment by SirBepis** [comment]
Bump,it needs an update after the patch.

**Comment by Lambda11** [comment]
@giggin pls don't troll ppl with wrong opcodes 👀 

closing as dupicate of https://github.com/Lambda11/let-me-fish/issues/38

**Comment by giggin** [comment]
Sorry I didn’t mean to troll. I used Alex pack logger and got those results

**Comment by Owyn** [comment]
OPcode numbers seem to be shifted on purpose in a way normal user wouldn't be able to notice, example:
25869 to 
25896
etc, so that's why that was called trolling
