### ISSUE TITLE
Problems with dismantling

### ISSUE THREAD

**Issue by StrayyChildd** [Lambda11/let-me-fish#44]
I've only tried this mod for the first time last week. It was great, seriously, the first day it fished for 14h in a row, no problem whatsoever. 
But last few days it gets stuck quite often while dismantling.
No crash, no other problem, and it continues just fine if I cancel the dismantle manually.
Tho I mostly use it while am at work, so canceling it manually ain't really the ideal for me.
I just wanted to ask if it is something that is normal to happen from time to time, or something that can be fixed. 
I appreciate since now the time to answer this.

(This is the message that appears while the problem is up)
<img width="960" alt="TERA_ScreenShot_20190416_064105" src="https://user-images.githubusercontent.com/49655860/56242645-a6b5cc00-6090-11e9-8d20-016c3cb17c60.png">

**Comment by Chiiruno** [comment]
turn off everful nostrum

**Comment by StrayyChildd** [comment]
Alrite, I'ma try that, thank you!
