### ISSUE TITLE
GM Mode

### ISSUE THREAD

**Issue by PatrickSantoZZ** [Lambda11/let-me-fish#46]
Hey is it possible to add an GM Mode like if a GM ports near you > Logout / Goto Char-Selection or just stop the fishing? :)

Would be really nice :)

**Comment by wtfteddy** [comment]
Sell fishlets would be nice too.

**Comment by wtfteddy** [comment]
@PatrickSantoZZ If you get Teleport the fishing stops.

**Comment by PatrickSantoZZ** [comment]
> Sell fishlets would be nice too.

yes that would be nice too

> @PatrickSantoZZ If you get Teleport the fishing stops.

ya i know but its not the best way to stop fishing , its better if a gm teleports to you , that the bot instantly stop the fishing :)

**Comment by Owyn** [comment]
> ts better if a gm teleports to you , that the bot instantly stop the fishing :)
yea, much better, that way GM would know for sure and instantly if you are cheating without even any further need for checks, cuz you'r pretty much confirming it that yourself with your own actions :-)

**Comment by SoliaRdi** [comment]
bot just turns off, so if you already fishing you switch to ingame auto fishing with 3 min delay etc

**Comment by Owyn** [comment]
Still, that's an action, which only happens when GM (in invisible mode also) appears near you.

lets see two situation:

1) GM appears near an ethical player - nothing happens, player continues as usual - gm confirms he's innocent

2) GM appears near a smartass gm-detecting player who does an action (stops fishing \ turns to autofishing \ smth else) as soon as a GM appears near him (hidden or not) - gm notices it and confirms he's guilty 100% with only that and can ban him right away

**Comment by SoliaRdi** [comment]
If you auto fishing then you 100% afk, why he would ping you? And this is not proof. 2nd, he know that you active fishing only by non gm account or by BAF messages, which you can skip

**Comment by Owyn** [comment]
> If you auto fishing then you 100% afk

I'm talking about stopping active-fishing and becoming afk fishing the moment GM arrives

> why would he ping you?

ping = finding cheaters, it's his job, not specifically finding someone, but everyone cheating

> he know that you active fishing only

logs can be checked for any time for what happened when a GM appeared in the area - how many ppl and how exactly stopped active-fishing \ stopping fishing at all at that moment, then mark them, then visit that area few more times and if they did that action again at the same moment GM appeared again = that's 100% confirms they are cheating and using GM mode

and that is 100% proof
1) such series of coincidences are not possible for ethical players
2) ethical people don't take any actions when a GM appears, especially one they can not notice at all

but ofc if GM team only consist of silly kids who can only play around with their GM panel, yea GM mode could help against them, but if (when) an adequate GM with a splinter of common sense appears - you'r doomed -> banned

**Comment by kriiszmae** [comment]
so having a gm mode is worst than non having one

**Comment by PatrickSantoZZ** [comment]
i think we can close this :x so no GM Mode is better then having one. If you get ported the Bot stopped :) 

Problem solved.
