### ISSUE TITLE
new function

### ISSUE THREAD

**Issue by lofuy** [Lambda11/let-me-fish#47]
i thinq it could be good too fusion the rootbeer and the let me fish. i don't know if it is possible :p. 
the most usefull thing about rootbeer was deleting some trash loot when you open the box. 
so i suggest you to code to auto-delete bait when we chose to craft worm. like this we use all filet or most of them and we can craft mass worm for our fishing mod :) 
or it could auto activate this mode if you have more than X filets :)

**Comment by Owyn** [comment]
There is no way in game to craft "worms", only riceballs, module uses both when maxed.
Worms are identical to riceballs in all terms, so there is no sense to prefer those, in terms of EXP for crafting you'd get less exp from wasting fillets on it than simple fishing a fish
