### ISSUE TITLE
na new maps

### ISSUE THREAD

**Issue by Phyxsyus** [Lambda11/let-me-fish#49]
I mapped new na maps for 344895

S_FISHING_BITE = 35300
C_END_FISHING_MINIGAME = 38335
C_START_FISHING_MINIGAME = 25869
S_START_FISHING_MINIGAME = 61667
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 46975

**Comment by Owyn** [comment]
gj but... https://github.com/Lambda11/let-me-fish/blob/master/opcodes/protocol.344895.map :eyes:

**Comment by Phyxsyus** [comment]
I didn't see that... well, i tried XD
