### ISSUE TITLE
Golden Fishes

### ISSUE THREAD

**Issue by StrayyChildd** [Lambda11/let-me-fish#50]
I know Let-Me-Fix does have some countermeasures against GM's attempts to catch it's users, but honestly I think that if they, for example, tp us right after fishing a golden fish, and we don't more or say anything, that alone would ring a lot of bells tbh. That being said, is it possible to add an option to fail on fishing gold fishes, so we can fish for 70h in a row without looking suspicious? :p
I appreciate any answer to this topic.

**Comment by Owyn** [comment]
Not moving or even exiting after Being teleported might seem pretty normal in Tera, considering how laggy and crashy it is...

Natural chance for BAF to appear is 1.0%

and I believe ethical players wouldn't fail those all the time, especially with max lvl rods and salads

So, not currently planned
