### ISSUE TITLE
SEA today patch

### ISSUE THREAD

**Issue by nicojelek** [Lambda11/let-me-fish#51]
S_FISHING_BITE = 20829
C_START_FISHING_MINIGAME = 57126
S_START_FISHING_MINIGAME = 41734
C_END_FISHING_MINIGAME = 45218
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 46584

can anyone confirm this is correct ? and where do i change this?  
tried change to 345891 still error.. : error running callback for command "fish"

**Comment by kath19x** [comment]
those OPCODES are correct but you a are editing the wrong file,  If you open mappings.json inside tera-data folder you will see the line

    "TH": {"version": 347377, "major_patch": 81, "minor_patch": 3, "protocol_hash": 

So what you need to edit is protocol.347377 to enter your new OPCODES

**Comment by Lambda11** [comment]
added new opcodes for RU and TH to opcodes folder in github

**Comment by nicojelek** [comment]
@kath19x ahh thx.. i understand now.. 
@Lambda11  thx and solved

**Comment by kath19x** [comment]
@Lambda11 add autosell to npc function instead of just dismantle please  on this mod :D
