### ISSUE TITLE
Auto-use skill advancement tomes

### ISSUE THREAD

**Issue by Chiiruno** [Lambda11/let-me-fish#52]
This may be slightly out of scope for this mod, but I don't really think it deserves it's own mod due to the main source of these being fishing.
Anyway, the idea is a command that detects and uses tomes I and II.
Something like `fish tome`.
Just tome I is fine too, since you don't get many tome II anyway.

**Comment by Owyn** [comment]
Yea, kinda absolutely out of scope :D 
cuz like even after a month of fishing you won't have a slot full of those tomes and need to get rid of em

Just when you'r done fishing and plan to play use https://github.com/Owyn/generic-box-opener-item-user to use those all at once quickly (use `boxdelay 100` for 10 tomes a second use or whatever cooldown there is)

**Comment by Chiiruno** [comment]
Well, there's a 3 second cooldown per-tome.
I guess that works though, thanks.
