### ISSUE TITLE
Chat messages in Russian and other

### ISSUE THREAD

**Issue by tehtelev** [Lambda11/let-me-fish#53]
Are you planning to translate the mod into Russian? I can help with this. 
My rice balls are not automatically used. Is this how it should be?
Please, add auto-dismantling of fishes, when auto-fishing is over due to the lack of bait.

**Comment by Owyn** [comment]
You can always just fork the github and maintain a russian version yourself if you believe it's worth it :shrug: cuz it's not planned

If something doesn't work - see README for instructions
