### ISSUE TITLE
Opcodes

### ISSUE THREAD

**Issue by wtfteddy** [Lambda11/let-me-fish#54]
Can someone Update the EU opcodes or show me a tutorial?

**Comment by SirBepis** [comment]
Bump,please update it.

**Comment by Owyn** [comment]
check pictures posted in https://github.com/Lambda11/let-me-fish/issues/38

**Comment by SirBepis** [comment]
If somebody gets the codes please let me know,thank you in advance.

**Comment by wtfteddy** [comment]
@Owyn Yeah i see it but what for Information u need need? Where i need to go? What should i type?

**Comment by Lambda11** [comment]
It's written where you need to go, and there's a readme there how to get opcodes, and list of opcodes you need are in previous protocol files

anyway, here's a EU opcode list (untested by me), try it and say if it fully works then I'll add it to the repository 
```
protocol.347373.map

S_FISHING_BITE = 22857
C_END_FISHING_MINIGAME = 46375
C_START_FISHING_MINIGAME = 36698
S_START_FISHING_MINIGAME = 58054
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 45778
```

**Comment by PreDeToRLinux** [comment]
I can confirm its working

**Comment by SirBepis** [comment]
It's working now.Thanks a lot ! @Lambda11

**Comment by wtfteddy** [comment]
@Lambda11 Where is it written? Only see the mode to catch the opcodes, but not how it works.

**Comment by Lambda11** [comment]
@wtfteddy in the readme of that module this mods readme refers to

added EU opcodes (after EU users submitted those to me) https://github.com/Lambda11/let-me-fish/commit/87b1a06adabafdf1b815781f91edd6ca147f44a2
