### ISSUE TITLE
where is a good example of config

### ISSUE THREAD

**Issue by trev44** [Lambda11/let-me-fish#58]
because once i downloaded this module -

and it set to my specific bait it crafted.
then fishing till inventory full.
then does not dismantle even if - 

{
	"dismantleFish": true,
	"dismantleFishGold": false,
	"craftId": 204102
}

the only reason i want to consider using your module is because Soliardi from other module doesnt have this auto-negotiate supported. which is really needed
![image](https://user-images.githubusercontent.com/48329651/58214646-cd51cd00-7cf6-11e9-9831-25b2fac55663.png)
am i suppose to add this contract id somewhere?

**Comment by Owyn** [comment]
You'r not supposed to edit config files
You'r not supposed to edit index.js file
You should have all opcodes & defs installed correctly

See if with all above it'd work fine (as it should)

**Comment by trev44** [comment]
well dismantling doesn't work for me as it is
is there a conflicting module?

**Comment by SoliaRdi** [comment]
i have diff naming in defs, so you should reinstall them
