### ISSUE TITLE
Need opcodes for SEA (patch 82) please

### ISSUE THREAD

**Issue by paplusplusplus** [Lambda11/let-me-fish#59]
Hi, I'm playing in SEA and I find out that this mod (let-me-fish) does not work for me since last update (patch 82// on 23 May 2019). So I'm not really sure whether it's because of my own pc or the mod needs update. tq

**Comment by Owyn** [comment]
You're most likely missing **opcodes** (which you should get on your own or just wait for others to get em and share those here later)

**Comment by paplusplusplus** [comment]
I see. Thank you very much for your answer :)

**Comment by andersonepk** [comment]
Update for us @Owyn, i tried but i m retarded so... fail haha
Good work by the way, i m using alot of your mods :)

**Comment by kriiszmae** [comment]
now eu aswell got new patch, so maybe they will fix the problem. Im having same issue now and im playing on eu server. waiting for update tyty

**Comment by DaXmAn** [comment]
in CaaliTeraProxy\node_modules\tera-data\map\protocol.350022.map

put these:
S_FISHING_BITE = 53982
C_END_FISHING_MINIGAME = 61011
C_START_FISHING_MINIGAME = 25633
S_START_FISHING_MINIGAME = 34452
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 45822

your welcome

**Comment by andersonepk** [comment]
> in CaaliTeraProxy\node_modules\tera-data\map\protocol.350022.map
> 
> put these:
> S_FISHING_BITE = 53982
> C_END_FISHING_MINIGAME = 61011
> C_START_FISHING_MINIGAME = 25633
> S_START_FISHING_MINIGAME = 34452
> C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 45822
> 
> your welcome
> 
> **p.s. I forget to mention that this is for EU :)**

SADDDDDD
I just tested dont work for me xD
Then i jsut read that is for EU T_T
well will be waiting some good soul appear then, thanks

![image](https://user-images.githubusercontent.com/18029568/58475121-7fd4c600-8123-11e9-962c-e7edd6347c09.png)

**Comment by kriiszmae** [comment]
working for eu now. ty much

**Comment by Lambda11** [comment]
added EU 82.05 opcodes into `opcodes` folder in the repo, remember to follow installation instructions from the README

as for SEA - seems like nobody is playing it enough for opcodes to appear here 🤷‍♂

**Comment by SirBepis** [comment]
Hmm doesn't work for me.Do I have to re-install the mod after adding the new OP codes?

**Comment by andersonepk** [comment]
NA boys, time to shineeeee   .... T_T

**Comment by paplusplusplus** [comment]
How sad :(((((

**Comment by LxMk864** [comment]
Change opcode not result

**Comment by ClarriceLSW** [comment]
S_FISHING_BITE = 47647
C_START_FISHING_MINIGAME = 46191
S_START_FISHING_MINIGAME = 40375
C_END_FISHING_MINIGAME = 51894
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 58231
sea op code. just dont know which protocol does it belong too

**Comment by Lambda11** [comment]
added sea opcodes https://github.com/Lambda11/let-me-fish/commit/088e28d5a4a230e5610e8cc654b12c056b457fd1
