### ISSUE TITLE
No delay in minigame

### ISSUE THREAD

**Issue by Kikomachin3** [Lambda11/let-me-fish#60]
Instantly catch during fish minigame and I did not make any changes on config file. I have the interact keybind to ~. Does it affect it?

**Comment by Owyn** [comment]
are you sure? because fishing minigame visually is just disabled and module plays it silently, only saying in proxy chat about it

what are your per fish stat times after catching like 10+ fishes? should be ~60 sec

**Comment by Kikomachin3** [comment]
attached a gif showing its instant. If its visually disabled on my screen only then its fine. I'm just concern if other players see it without animation of my character struggling when catching. 

https://media.giphy.com/media/eN4FdWItDjBX1qpDww/giphy.gif

**Comment by Kikomachin3** [comment]
I fished out 87 fishes. 62 sec per fish.

**Comment by Owyn** [comment]
That's the finish animation when you catch a fish, everybody does the same, it's fine.
