### ISSUE TITLE
Not really an issue but a question that has heavy impact.

### ISSUE THREAD

**Issue by SirBepis** [Lambda11/let-me-fish#61]
So,what are the consequences of getting caught while bot fishing?At the start of the patch I have seen people getting moved from a GM and if they kept fishing they would be banned for fourteen days.Later tho, Gameforge permabanned a lot of people at once without any fourteen-days suspension before and with no warning.Any thoughts?

(feel free to delete this thread if it's not allowed/relevant)

**Comment by Owyn** [comment]
Not even sure if it's still happening (bans) after that big banwave after which all fish manager modules made it so fishing would stop after being teleporting
