### ISSUE TITLE
dispatch hook unmapped packet error after recent update. 

### ISSUE THREAD

**Issue by Serisse** [Lambda11/let-me-fish#64]
I have read the "code" page explaining why this error occurs, however I have never had this error before because everything was installed correctly. After my game update today, though, I am receiving this error. I re-downloaded and replaced the opcodes and defs files, but that hasnt fixed anything. Not sure what's going on but I believe it is related to the latest update.

**Comment by TeraPlayer1994** [comment]
I think we gotta wait until they update the def, and opcode files. They still are old files and the update may have changed things that isn't compatible with our old code.

**Comment by Serisse** [comment]
Yeah i was wondering about that, but i figured I would post about it just in case the creator of this mod wasnt aware of it yet =P

**Comment by Lambda11** [comment]
Added new NA opcodes file.

in future please refer to opened https://github.com/Lambda11/let-me-fish/issues/38 issue
