### ISSUE TITLE
Dear Lambda11 users. SelltoNpc?????

### ISSUE THREAD

**Issue by trev44** [Lambda11/let-me-fish#68]
Dear Lambda11 users, what are you doing with all the fish filet??????????
To the coder... why waste time selling cooking buffs when you can switch to selling fish to merchant all day.
switch back to making filet during the night so we have bait for the day.

Reason why i stress this, is because SoliaRdi from other auto fisher isn't as dedicated i suppose.
The C_STORE_COMMIT is not working and now we are left fileting forever till he responds???  
the Opcodes are right, any ideas how to self fix?

**Comment by Lambda11** [comment]
🤷‍♀
