### ISSUE TITLE
Auto dismantling is not working(saying that im busy)

### ISSUE THREAD

**Issue by Zarruv** [Lambda11/let-me-fish#69]
Newest version of module, zero modifications in it. But auto dismantling is not working(saying that im busy)
Also fresh proxy only standard modules
![изображение](https://user-images.githubusercontent.com/52708964/60895793-ea723900-a26d-11e9-8523-62fbcdce21d3.png)

**Comment by Lambda11** [comment]
You can thank @PinguinRei for sabotaging RU opcodes :angry: 

Pushed a fix https://github.com/Lambda11/let-me-fish/commit/fb03697fb1ec06e37e7f4d4e8c606a0ba1e40c0c reinstall opcodes for the fix
