### ISSUE TITLE
OP codes EU

### ISSUE THREAD

**Issue by SirBepis** [Lambda11/let-me-fish#70]
Hello,after the latest patch on EU you need the OP codes to keep fishing.If anybody has them feel free to share them as I would need them too.

**Comment by Lambda11** [comment]
try https://github.com/Lambda11/let-me-fish/blob/09091b92808b83a127a85590f8e2a013f788af40/opcodes/protocol.353338.map

**Comment by SirBepis** [comment]
Hello again,i downloaded the mod and I keep getting this error.Mind giving a look?
![Screenshot_1](https://user-images.githubusercontent.com/49036357/61739088-6acb8a80-ad94-11e9-9877-ec1cd1cb84cc.png)
![Screenshot_2](https://user-images.githubusercontent.com/49036357/61739095-6d2de480-ad94-11e9-9524-05ad6adb285d.png)
![Screenshot_3](https://user-images.githubusercontent.com/49036357/61739099-6e5f1180-ad94-11e9-8cf5-1847566b4008.png)

**Comment by crysis4000** [comment]
Hello !
I tried these opcodes, but they don't work.
So, I tried to get these opcodes with debug-logger, but i didn't find fishing associated events ...
How did you find these opcodes ?

Thank you !

**Comment by Owyn** [comment]
@crysis4000 
> How did you find these opcodes ?
By fishing

**Comment by Owyn** [comment]
@SirBepis 

Looks like you installed it wrong, didn't unzip or folder inside folder, just wrong

**Comment by crysis4000** [comment]
> @crysis4000
> 
> > How did you find these opcodes ?
> 
> By fishing

I did that, but my logger didn't show fishing events opcodes ...

**Comment by Owyn** [comment]
Have you installed .def files? those are needed @crysis4000

**Comment by crysis4000** [comment]
Yep, I have this mod before today's game update, worked very well.
After today's game update, i only have downloaded the new opcodes/protocol.353338.map and placed in <mod folder>/opcodes.

When i type the command "fish", proxy recognize the mod, but it also displays "Error running callback for command 'fish'."
And when i fish, it doesn't trigger the auto fish, and in TeraToolbox logs, they show : 
![Annotation 2019-07-23 220244](https://user-images.githubusercontent.com/13242882/61743975-8899ef00-ad96-11e9-8f3a-fbcc96f0d664.png)

**Comment by Owyn** [comment]
putting anything into `/opcodes` folder does nothing, please see #installation part of the readme, or just use Pinky proxy which is now oficially `fishy` cuz it ships all the opcodes https://github.com/tera-proxy/tera-data/blob/0b0ef1521e286ae09b89626a8081a408a5b024ec/map/protocol.353338.map

**Comment by crysis4000** [comment]
FML, i forgot installation process

Thank you ! :)

**Comment by SirBepis** [comment]
I keep getting the same error even tho I didn't unzip and installed it correctly.

**Comment by crysis4000** [comment]
@SirBepis in "mods" folder, does "let-me-fish" folder is named "let-me-fish-master" ?

**Comment by SirBepis** [comment]
Ok , fixed.There was a folder inside another folder

**Comment by Lambda11** [comment]
https://github.com/Lambda11/let-me-fish#installation
now all opcodes come from Pinky, take note to ask him for codes instead of waiting here :-)
