### ISSUE TITLE
NA OPcodes

### ISSUE THREAD

**Issue by palvaloo** [Lambda11/let-me-fish#74]
Needs new opcodes for v85 NA

**Comment by Owyn** [comment]
@palvaloo please see https://github.com/Lambda11/let-me-fish#Installation on how to get them

**Comment by palvaloo** [comment]
Some opcodes for some reason dont work with packet Id logger (they wont show even when you try to invoke). I saw last time u posted a link to Pinkie github for them but it is not a full updated list

**Comment by Owyn** [comment]
> Pinky
Probably limited opcodes forked from Caali are just temporary there, not sure

**Comment by palvaloo** [comment]
S_FISHING_BITE = 26642
C_START_FISHING_MINIGAME = 27796
S_START_FISHING_MINIGAME = 25468
C_END_FISHING_MINIGAME = 23433
C_RQ_ADD_ITEM_TO _DECOMPOSITION_CONTRACT = 34024
C_MEDAL_STORE_BUY_ADD_BASKET = 42279
C_MEDAL_STORE_COMMIT = 42255
C_PUT_WARE_ITEM = 22417
C_STORE_COMMIT = 55306
C_STORE_SELL_ADD_BASKET = 64551
S_FISHING_CATCH = 51024
S_MEDAL_STORE_BASKET = 53280
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 31998
S_START_FISHING_MINIGAME = 63810
S_STORE_BASKET = 39506
