### ISSUE TITLE
New version(85.06) auto-decomposition is not available

### ISSUE THREAD

**Issue by q848899** [Lambda11/let-me-fish#75]
The old decomposition window is opened by other windows

**Comment by Owyn** [comment]
what

**Comment by Foks5000** [comment]
> what

Тип контракта поменяли с 89 на 90

**Comment by Owyn** [comment]
> 90

в auto-fishing он всё ещё 89... т.к. тестить возможности нет, подожду сперва исправления там для верности

**Comment by q848899** [comment]
Thank you
Solved the problem.

**Comment by Owyn** [comment]
how did you solve it? 🤔

**Comment by q848899** [comment]
Change type 89 to 90

**Comment by Lambda11** [comment]
Updated latest version, now dismantle should work fine by default.
