### ISSUE TITLE
fishing cancels after 1 fish

### ISSUE THREAD

**Issue by silvermane2000** [Lambda11/let-me-fish#76]
after every single try fishing cancels /w messages below
![TERA_ScreenShot_20190823_212254](https://user-images.githubusercontent.com/54438035/63615248-8cb36980-c5ed-11e9-8c77-c6c30844fce9.png)

**Comment by Owyn** [comment]
is your region on Patch 85 already?

**Comment by silvermane2000** [comment]
yes, russian server
i tried before and after mod updating with actual opcodes, but nothing just this error

**Comment by silvermane2000** [comment]
> is your region on Patch 85 already?

yes, russian server
i tried before and after mod updating with actual opcodes, but nothing just this error

**Comment by Lambda11** [comment]
Try latest version and see the message on how many items it says you have in the inventory

+ does crafting also not work if you have enough fish fillets? Try having more fillets in inventory

**Comment by silvermane2000** [comment]
thats what happenning in normal mode 
it doesnt see the stuff needed to fish 
but as you can see i have everything
![TERA_ScreenShot_20190823_224413](https://user-images.githubusercontent.com/54438035/63620723-bde66680-c5fa-11e9-8e3c-9e0ae6196f61.png)
![TERA_ScreenShot_20190823_230302](https://user-images.githubusercontent.com/54438035/63620724-bde66680-c5fa-11e9-8098-a4bb4449dd3d.png)

**Comment by Lambda11** [comment]
I see, try now, pushed an updat

**Comment by palvaloo** [comment]
It works @Lambda11

**Comment by palvaloo** [comment]
Also @Lambda11 
NA Opcodes
S_FISHING_BITE = 26642
C_START_FISHING_MINIGAME = 27796
S_START_FISHING_MINIGAME = 25468
C_END_FISHING_MINIGAME = 23433
C_RQ_ADD_ITEM_TO _DECOMPOSITION_CONTRACT = 34024
C_MEDAL_STORE_BUY_ADD_BASKET = 42279
C_MEDAL_STORE_COMMIT = 42255
C_PUT_WARE_ITEM = 22417
C_STORE_COMMIT = 55306
C_STORE_SELL_ADD_BASKET = 64551
S_FISHING_CATCH = 51024
S_MEDAL_STORE_BASKET = 53280
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 31998
S_START_FISHING_MINIGAME = 63810
S_STORE_BASKET = 39506

**Comment by palvaloo** [comment]
Would it be possible to take a look at your fish filet delete mod? It be super handy to have cuz  this stops at 10k filets

**Comment by silvermane2000** [comment]
> I see, try now, pushed an updat

works perfect for now. 
big thanks!

**Comment by Lambda11** [comment]
@palvaloo updated fish-deleted, should work now (probably) (lets hope it'd delete right items 💃 , can't test)

**Comment by palvaloo** [comment]
Getting someone to test rq, but thanks for your responsiveness :-D

**Comment by palvaloo** [comment]
Actually ill just tweak it to the amount of fish filets i have right now and test it, one sec

**Comment by palvaloo** [comment]
It works, thank you!
