### ISSUE TITLE
opcodes for NA not updated?

### ISSUE THREAD

**Issue by Haru-Kasugano** [Lambda11/let-me-fish#78]
Howdy, followed the installation and put the opcodes from pinky in the correct spot, but I'm still getting the error:

[05:51:31.334] [command] ERROR: Error: [dispatch] [let-me-fish] hook: unmapped packet "S_START_FISHING_MINIGAME"

Are the opcodes just not updated for NA patch 85 yet?

**Comment by Owyn** [comment]
Yea, not updated, Pinky promised full opcodes when all regions hit Patch 85

you might want to try https://github.com/SoliaRdi/auto-fishing/blob/master/protocol.354502.map opcode file meanwhile

**Comment by Haru-Kasugano** [comment]
That works! Thanks!

**Comment by Haru-Kasugano** [comment]
So I used those opcodes and everything was fine for about a day. But then, this morning my game instantly crashed to client as I hit enter on the !fish command in /8 chat. Cali proxy had an error that said unexpected crash due to model/hack detection or something of that regard. 

Has anyone else had this issue? Is it even likely that Enmasse could have detected it? Ban hammer?

**Comment by Owyn** [comment]
Are you sure you'r not using Pinky proxy?

and yea, screenshots would help...

**Comment by Haru-Kasugano** [comment]
I'm using TeraToolbox and had just added the opcode from the link you sent me to where the opcodes from pinky would have been. As for screenshots, I just ended up closing everything after and havent tried since, but the error was the same as a previous screenshot from the "disconnecting" issue on this forum except it was in red of course. 
![image](https://user-images.githubusercontent.com/54484040/63695225-d9f62d80-c7dd-11e9-8f1d-9decf38c1654.png)

**Comment by Owyn** [comment]
says "unstable internet connection" there, if it's just you with the problem that might be more than plausible
