### ISSUE TITLE
Dismantle seems broken with new patch

### ISSUE THREAD

**Issue by Thatguy6104** [Lambda11/let-me-fish#79]
I might've missed something, updated everything, had a lot of issues with OP codes, finally got it to work, and now it fishes until inventory is full and then gets stuck trying to dismantle. Anything I may have missed?

**Comment by Owyn** [comment]
Make sure you have right .def's installed and everything else, that guy https://github.com/Lambda11/let-me-fish/issues/77 also had a problem but in the end it was working fine for him, so it must be something during installation you've done wrong

**Comment by SirBepis** [comment]
@Thatguy6104 Hello there.Could you please post the OP codes so I can copy them?Thank you in advance.

**Comment by Owyn** [comment]
@SirBepis https://github.com/tera-proxy/tera-data/tree/master/map

**Comment by SirBepis** [comment]
@Owyn Thank you!
