### ISSUE TITLE
after patch 85

### ISSUE THREAD

**Issue by kriiszmae** [Lambda11/let-me-fish#80]
![image](https://user-images.githubusercontent.com/47244732/63854063-8c73ef00-c99c-11e9-8ba5-ee53edc56d43.png)

**Comment by Owyn** [comment]
@kriiszmae kriis https://github.com/Lambda11/let-me-fish#Installation

**Comment by kriiszmae** [comment]
oh so i need to reinstall the module?..but opcodes dnt seem to be updated

**Comment by kriiszmae** [comment]
nvm i got it. i didn't take pinki opcodes
