### ISSUE TITLE
Can i set this mod to cancel goldfish?

### ISSUE THREAD

**Issue by paplusplusplus** [Lambda11/let-me-fish#82]
I don't need any goldfish and I don't want the server to show my name. so can I set this mod to cancel every eating-bait goldfish? and how? thank you in advance :)

**Comment by kriiszmae** [comment]
u can set the mod to dismantle goldfish like any other fish. Just type /8 fish gold and then save.

**Comment by Lambda11** [comment]
Ppl skipping goldfishes = obvious cheaters 😺
