### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by ascit1234545** [Lambda11/let-me-fish#84]
I have put the defs insides to tera-data/protocol and ı have updated tera-data opcodes. I use teratoolbox proxy. I thought this was all ı needed to do to get this to work. I launched the teratoolbox and ingame ı tried !fish, fish, /8 fish, /8 !fish but none worked. Am I missing something or did I miss some steps?
Thanks in advance.

**Comment by Owyn** [comment]
see console for errors and if the module was even installed and loaded in the first place

**Comment by ascit1234545** [comment]
I think not, there isn't any mods related to fishing being displayed in the ''my mods'' folder. And ı didnt get any errors that has anything about fishing.So how am I loading the mod into tera toolbox again?

**Comment by ascit1234545** [comment]
I thought putting the defs insides is enough?

**Comment by Owyn** [comment]
putting defs only puts the defs, how are you expecting the mod to work if you've never installed it?

**Comment by ascit1234545** [comment]
Sorry but in the installation tab this is what was written and ı just followed the steps. Where do I download the mod from? Also I appreciate your dungeon guides, they helped me so much.

**Comment by ascit1234545** [comment]
I am dumb. Thank you for bearing with me.
