### ISSUE TITLE
No animation trying to pull fish

### ISSUE THREAD

**Issue by kittytera** [Lambda11/let-me-fish#87]
I have used this mod before and it used to have that animation when there's a bite and a character trying to pull fish (during minigame) Now I came back and use this but it doesn't have that animation anymore. A character just stands waiting a bite and when it does the character just suddenly pull fish in. So it looks kinda unnatural. How can I fix this? Or it is meant to be like this?

**Comment by Lambda11** [comment]
Client-side only
