### ISSUE TITLE
Error: Module "let-me-fish-master" uses the following outdated/unsupported packets

### ISSUE THREAD

**Issue by rongnhatgan** [Lambda11/let-me-fish#9]
Hi, how can I solve this problem ? I followed the Installation guide and stuck at this, I'm at Tera SEA (Playwith) server. Thank you ! 
![letmefish](https://user-images.githubusercontent.com/46210689/50503119-02832780-0a97-11e9-8819-1b0a844aaee5.png)

**Comment by Owyn** [comment]
you can solve it by following [Installation part](https://github.com/Lambda11/let-me-fish#installation)... in the readme :|
