### ISSUE TITLE
Will not dismantle. Reinstalled and still nothing. 

### ISSUE THREAD

**Issue by Twinbrow** [Lambda11/let-me-fish#94]
![image](https://user-images.githubusercontent.com/57502204/69009399-ac66df00-0909-11ea-9512-5b8b4645bfd1.png)
it's not pulling anything over so its empty when it tries.

**Comment by Owyn** [comment]
are you sure you have correct opcodes? it seems to be working for others :thinking:

else only https://github.com/Owyn/PacketsLogger could tell what's wrong by logging how module tries to put in a fish and how it is done when you do it yourself

**Comment by Twinbrow** [comment]
I have all the opcodes from NA. Its only when I drop the opcode from this script that is has errors.  When I updated it back, it stopped working completely.  Stuck in a loop. Tried proxy and toolbox. 

[11:01:34.935] [command] ERROR: Error: [dispatch] [let-me-fish] hook: unmapped packet "S_START_FISHING_MINIGAME"

**Comment by Owyn** [comment]
Well yea, opcodes are needed, correct ones ofc

Try to use PacketsLogger to see what's wrong to be able to fix it

**Comment by Twinbrow** [comment]
Got it figured out. Had everything correct, but the opcode that was dropped into "map" from this mod was causing it to not read the Check_Version because it was reading out of order.  Having fun and learning a lot. Thank you for your help. I'm not really an "automate it" kind of person, but it was fun learning how this stuff works.  Thank you again for your help. Had more fun learning this than playing the game.
